Feature/eodhp 654 expose workflow as a user service
EO-DataHub/eoepca-proc-service-template pull request #14
Opened 2024-11-19 16:36 UTC by tjellicoe-tpzuk

## Add new inputs to support user-services
- Pass through the calling and executing workspace names
- Pass the user token through to the stagein for AWS IAM authentication
- Pull in some changes from upstream

2024-11-19 17:02 UTC, apalmer-tpzuk requested changes

2024-11-19 17:02 UTC, apalmer-tpzuk commented on {{cookiecutter.service_name}}/service.py
> +import boto3
boto3 imported twice

2024-11-19 17:02 UTC, apalmer-tpzuk commented on {{cookiecutter.service_name}}/service.py
> +
Not sure what this is accomplishing except for logging - pod_name, service_account, and service_account_token don't seem to be used. If it is just logging then I think this should be somewhere other than reading specifically an s3 file.

2024-11-19 17:02 UTC, apalmer-tpzuk commented on {{cookiecutter.service_name}}/service.py
> +            executing_namespace = calling_workspace["spec"]["namespace"]
Getting the calling workspace seems to only be used in the case where calling=executing - Therefore can we simplify and just get the executing workspace in every case?

2024-11-21 09:44 UTC, tjellicoe-tpzuk commented on {{cookiecutter.service_name}}/service.py
> +import boto3
removed

2024-11-21 09:44 UTC, tjellicoe-tpzuk commented on {{cookiecutter.service_name}}/service.py
> +
yep just logging, now removed

2024-11-21 09:53 UTC, tjellicoe-tpzuk commented on {{cookiecutter.service_name}}/service.py
> +            executing_namespace = calling_workspace["spec"]["namespace"]
Good point, removed duplicate

2024-11-21 11:42 UTC, apalmer-tpzuk approved these changes

2024-11-25 16:02 UTC, apalmer-tpzuk commented on {{cookiecutter.service_name}}/service.py
> +        config.load_incluster_config()
Do we need to load kubeconfig again? As it was loaded before execution, line 465

2025-01-02 13:38 UTC, tjellicoe-tpzuk commented on {{cookiecutter.service_name}}/service.py
> +        config.load_incluster_config()
removed

2025-01-02 14:41 UTC, apalmer-tpzuk commented on {{cookiecutter.service_name}}/service.py
> +        inputs["KEYCLOAK_CLIENT_SECRET"]["value"] = os.getenv("KEYCLOAK_CLIENT_SECRET")
Where does this get used?

2025-01-03 12:26 UTC, tjellicoe-tpzuk commented on {{cookiecutter.service_name}}/service.py
> +        inputs["KEYCLOAK_CLIENT_SECRET"]["value"] = os.getenv("KEYCLOAK_CLIENT_SECRET")
This is used in the stage-in [here](https://github.com/UKEODHP/ades-stagein/blob/main/stage.py#L176)

2025-01-03 12:26 UTC, tjellicoe-tpzuk commented on {{cookiecutter.service_name}}/service.py
> +        inputs["KEYCLOAK_CLIENT_SECRET"]["value"] = os.getenv("KEYCLOAK_CLIENT_SECRET")
This is seemingly the only way to insert secrets into the workflow steps

2025-01-13 10:14 UTC, apalmer-tpzuk approved these changes

2025-01-13 13:53 UTC, merged